export const events = [
    {
        id: "EVT1A",
        name: "ورشة عمل برمجة بايثون",
        category: "تعليمي",
        date: "2025-06-10",
        location: "قاعة الحاسوب - مبنى A",
        participants: 45,
        capacity: 50,
        attendanceRate: 0.9,
        organizer: "قسم علوم الحاسوب",
        rating: 4.7,
        description: "ورشة لتعليم أساسيات البرمجة بلغة بايثون للطلاب."
    },
    {
        id: "EVT2B",
        name: "مباراة كرة القدم الجامعية",
        category: "رياضي",
        date: "2025-06-12",
        location: "استاد الجامعة",
        participants: 100,
        capacity: 150,
        attendanceRate: 0.66,
        organizer: "النوادي الرياضية",
        rating: 4.5,
        description: "مباراة بين فرق الجامعة للمرحلة الجامعية."
    },
    {
        id: "EVT3C",
        name: "المعرض الفني السنوي",
        category: "ثقافي",
        date: "2025-06-15",
        location: "قاعة المعارض - مبنى F",
        participants: 200,
        capacity: 250,
        attendanceRate: 0.8,
        organizer: "قسم الفنون الجميلة",
        rating: 4.8,
        description: "عرض أعمال الطلاب الفنية السنوية."
    },
    {
        id: "EVT4D",
        name: "ندوة عن الذكاء الاصطناعي",
        category: "تعليمي",
        date: "2025-06-20",
        location: "مدرج 2 - مبنى C",
        participants: 75,
        capacity: 100,
        attendanceRate: 0.75,
        organizer: "قسم علوم الحاسوب",
        rating: 4.6,
        description: "ندوة علمية عن تطورات الذكاء الاصطناعي."
    },
    {
        id: "EVT5E",
        name: "يوم التوظيف",
        category: "مهني",
        date: "2025-06-25",
        location: "قاعة المؤتمرات",
        participants: 150,
        capacity: 200,
        attendanceRate: 0.75,
        organizer: "مكتب التدريب والتوظيف",
        rating: 4.7,
        description: "فعاليات لمقابلة الشركات للطلاب والخريجين."
    },
    {
        id: "EVT6F",
        name: "مهرجان الطعام الصحي",
        category: "ثقافي",
        date: "2025-07-01",
        location: "الساحة الرئيسية",
        participants: 120,
        capacity: 150,
        attendanceRate: 0.8,
        organizer: "قسم التغذية",
        rating: 4.5,
        description: "مهرجان للتوعية بالأكل الصحي وتقديم عينات."
    },
    {
        id: "EVT7G",
        name: "بطولة كرة السلة الجامعية",
        category: "رياضي",
        date: "2025-07-05",
        location: "صالة الرياضة - مبنى B",
        participants: 80,
        capacity: 100,
        attendanceRate: 0.8,
        organizer: "النوادي الرياضية",
        rating: 4.6,
        description: "منافسة بين الفرق الجامعية لكرة السلة."
    },
    {
        id: "EVT8H",
        name: "مسابقة تصميم الويب",
        category: "تعليمي",
        date: "2025-07-10",
        location: "قاعة الحاسوب - مبنى A",
        participants: 60,
        capacity: 70,
        attendanceRate: 0.85,
        organizer: "قسم علوم الحاسوب",
        rating: 4.8,
        description: "مسابقة لأفضل تصميم مواقع إلكترونية من الطلاب."
    },
    {
        id: "EVT9I",
        name: "ورشة خط عربي",
        category: "ثقافي",
        date: "2025-07-15",
        location: "قاعة الفنون - مبنى F",
        participants: 40,
        capacity: 50,
        attendanceRate: 0.8,
        organizer: "قسم الفنون الجميلة",
        rating: 4.7,
        description: "تعلم أساسيات الخط العربي للطلاب."
    },
    {
        id: "EVT10J",
        name: "ندوة التوظيف الذاتي",
        category: "مهني",
        date: "2025-07-20",
        location: "قاعة المؤتمرات",
        participants: 70,
        capacity: 80,
        attendanceRate: 0.875,
        organizer: "مكتب التدريب والتوظيف",
        rating: 4.6,
        description: "ورشة عمل حول تطوير مهارات التوظيف الذاتية."
    }
];